{
 "title": "Host Stats",
 "description": "Basic host stats: CPU, Memory Usage, Disk Utilisation",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg without (cpu)(irate(node_cpu{job=\"node_exporter\",mode!=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{job='node_exporter'} - node_memory_MemFree{job='node_exporter'} - node_memory_Buffers{job='node_exporter'} - node_memory_Cached{job='node_exporter'}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers{job='node_exporter'}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Buffers{job='node_exporter'}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_Buffers{job='node_exporter'}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Disk I/O Utilisation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_ms{job='node_exporter',device!~'^(md\\\\d+$|dm-)'}[5m]) / 1000",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}